services:
  postgres:
    image: postgres:16
    container_name: magicvs-postgres
    environment:
      POSTGRES_DB: magicvs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: magicvs-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magicvs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DECK_MIN_CARDS: 60
      SMTP_USER: "noreplymagicvs@gmail.com"
      SMTP_PASS: "qhxmzwbsoozavefg"
      SMTP_FROM: "noreplymagicvs@gmail.com"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: magicvs-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
